[env]
LANG = "en_US.UTF-8"
NVIM_THEME = "dark"
SHELL = "zsh"
TERM = "xterm-256color"

[font]
size = 10.0

[font.offset]
y = 2

[font.glyph_offset]
y = 1

[font.normal]
family = "Lilex Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Lilex Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Lilex Nerd Font Mono"
style = "Italic"

[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"

[colors.normal]
black = "0x282828"
red = "0xcc241d"
green = "0x98971a"
yellow = "0xd79921"
blue = "0x458588"
magenta = "0xb16286"
cyan = "0x689d6a"
white = "0xa89984"

[colors.bright]
black = "0x928374"
red = "0xfb4934"
green = "0xb8bb26"
yellow = "0xfabd2f"
blue = "0x83a598"
magenta = "0xd3869b"
cyan = "0x8ec07c"
white = "0xebdbb2"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
option_as_alt = "Both"

[terminal.shell]
program = "zsh"
args = ["-l", "-c", "zellij attach -c main"]

[bell]
animation = "EaseOutExpo"
duration = 0

[[keyboard.bindings]]
key = "W"
mods = "Control|Shift"
action = "Quit"

[[keyboard.bindings]]
key = "F"
mods = "Control|Super"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "Enter"
mods = "Shift"
chars = "\u001B\r"

[[keyboard.bindings]]
key = "Equals"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"
